
name: MVS/CE Sysgen Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
# Sysgen
  mvsce-sysgen:
    name: MVS 3.8j System Generation Release
    runs-on: [ubuntu-latest]
    timeout-minutes: 70
    container: mainframed767/hyperion:develop

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Move MVS/CE sysgen
        run: |
          mkdir -p /mvsce/
          mv * /mvsce/
        shell: bash

      - uses: BSFishy/pip-action@v1
        with:
          packages: colorama

      - name: Get git tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Running sysgen.py
        id: sysgen
        working-directory: /mvsce
        run: until ./sysgen.py --release --timeout 500 --version ${{steps.tag.outputs.tag}} --CONTINUE; do echo "Failed, rerunning"; done

      - name: Printing Debug Log
        if: ${{ always() && (steps.sysgen.outcome == 'failure') }}
        working-directory: /mvsce
        run: cat sysgen.log

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: ${{ github.event.release.tag_name }}
          prerelease: false
          title: "MVS/CE Sysgen"
          files: |
            /mvsce/MVSCE/README.md
            /mvsce/MVSCE.release.*.tar
