
name: MVS/CE Sysgen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
# Sysgen
  mvsce-sysgen:
    name: Generating Sysgen
    runs-on: [ubuntu-latest]
    container: mainframed767/hyperion:latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Move MVS/CE sysgen
        run: |
          mkdir -p /mvsce/
          mv * /mvsce/
        shell: bash

      - name: Sysgen
        working-directory: /mvsce
        run: ./sysgen.py

      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: Current MVS/CE Release
