
name: MVS/CE Sysgen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
# Sysgen
  mvsce-sysgen:
    name: Generating Sysgen
    runs-on: [ubuntu-latest]
    container: mainframed767/hyperion:latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Move MVS/CE sysgen
        run: |
          mkdir -p /mvsce/
          mv * /mvsce/
        shell: bash

      - uses: BSFishy/pip-action@v1
        with:
          packages: colorama

      - name: Running sysgen.py
        id: sysgen
        working-directory: /mvsce
        run: ./sysgen.py --release

      - name: Printing Debug Log
        if: failure()
        working-directory: /mvsce
        run: cat sysgen.log

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Build"
          working-directory: /mvsce
          files: |
            MVSCE/README.md
            MVSCE.release.*.tar
